#!/bin/bash
for value in {1..5}
do
echo "commit - $value"  >> commits-sample.txt
git add .
git commit -m "PIP-10: Including validations - $value" 
git push
done

for value in {1..5}
do
echo "commit - $value"  >> commits-sample.txt
git add .
git commit -m "PIP-13: Including validations - $value" 
git push
done

for value in {1..5}
do
echo "commit - $value"  >> commits-sample.txt
git add .
git commit -m "PIP-14: Including validations - $value" 
git push
done

for value in {1..5}
do
echo "commit - $value"  >> commits-sample.txt
git add .
git commit -m "PIP-1: Including validations - $value" 
git push
done

