#!/usr/bin/expect -f
set timeout -1 
spawn ./commitLoop
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# # 20
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# # 30
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# # 40
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"

# # 50

# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"

# # 60
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# # 70
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# # 80
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# # 90
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# # 100
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
# expect "Password for 'http://gitea_admin@localhost:4000':"
# send -- "password\r"
expect eof